FROM teracy/ubuntu:16.04-dind-latest

RUN apt-get update -y && apt-get install -y \
    libgnutls30

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CE7709D068DB5E88 \
    && add-apt-repository "deb https://repo.sovrin.org/deb xenial stable"

RUN apt-get update -y