FROM ubuntu:18.04
RUN apt-get update -y && apt-get install -y \
    gnupg \
    software-properties-common \
    apt-transport-https \
    ca-certificates

# RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CE7709D068DB5E88
# # RUN echo "deb https://repo.sovrin.org/sdk/deb bionic stable" >> /etc/apt/sources.list
# RUN add-apt-repository "deb https://repo.sovrin.org/sdk/deb bionic stable"
# RUN apt-get update -y && apt-get install -y \
#     libindy libnullpay