FROM ubuntu:20.04
RUN apt-get update -y && apt-get install -y \
    gnupg \ 
    ca-certificates

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CE7709D068DB5E88
RUN echo "deb https://repo.sovrin.org/sdk/deb bionic stable" >> /etc/apt/sources.list
RUN apt-get update -y && apt-get install -y \
    libindy